language: generic
services:
  - docker
sudo: required
install:
  - docker-compose build
script:
  - docker-compose up -d
  - docker-compose exec nuxt npm run lint
  - docker-compose exec nuxt npm run sequelize db:migrate
  - docker-compose exec nuxt npm run sequelize db:seed:all
  - docker-compose exec nuxt npm test
  - docker-compose down
deploy:
  - provider: script
    script: ./scripts/deploy-docker-hub.sh
    skip_cleanup: true
after_deploy:
  - ./scripts/trigger-github-deploy.sh
env:
  global:
    # DOCKER_USERNAME
    - secure: PC9cYzOPyVQAfx+kFoHC5gGvnvcgQiOPQeNZv/to+S+Sh9g7NE+ATrLZLDJDQlCePhOSB+2HA1n/cmMXhyT4D3eiYXSlCbkme5Zr78Ss+FkSVPxNdp4O6FxC4qiACeCpNQ4090HI+SfJOcZdF6DAMR0Sgff4qKd0w03bsRTdkKtfPnUkhB3/R86rzXkNFGSSHcp802yVdNIDoyY5P/5zasKCN/oslw1WhhmwMC8Mh63rNSnTAFru1101wbUMGUr1wMluoygsYDW6A5/kzgNBQyJVV4eH7CSD29COSLyjGUyf+iGYBMSWfJ4bCOjKkvv6lgSiah8Bf65W26PGZ/zzSwF/3h+X+Pprlp1Aj16SIzGB+pRg4zvPMGKs1NmEANrpkBPGBLnaPlfXocTI5WImX4ykFz9qCZtjQl7U7U67sSshevyebmvVrfD2i+65iRHecnEMjTf9doHtYg0V1Rr82q8Am4vW/U5vTq3kIx2xBsgsPed0bYaoUv9EEiJIS9NSWx6caNCC+A4b0t4rHAapspwAJBbotuhZKDMSfsNygfdyhff6bbXALsHtrwb0ocpxPkH8igbp/phzdiUmzW34TiXJZKES5o10wUhbDgPJDETWAsgsC1+svd2tczEvaXy8Sk2n4X+TilrLPVt57ugPDZee5MSDAm8wq4NjBj7r46s=
    # DOCKER_PASSWORD
    - secure: d8zIElU2Hx15AVsWE/8rN6gyaHPMwGNZrLp3DRtTj36X1vDbGlLkR9KsR09lgAUSkK94xHVP0GxbKtUOrk/ZYg2ZGAvEYLrq/HNE2CQa+3AiDuooDcfcfvExr2QrpS9scgX28foblLY3KmZ8YvxPISQ3W2fWe6iSdPYx01AvlFYk9DsEhQtQ7PEKpJgd7FKhWokwj4mKCevtShCwBRAAwIB++LdmIKuJSwpRDBw5jVvVoUda9EGbMnStAk1xFmbu6p0zZOhnIkkr4EhnN1s2/T5lHTVupLnF3uAusmUAhC5c3RLYNmNB+9MzcSKBmhXv6TaeDmGovxN9VW10mIhsDAQqARqNNjXxeG2ZpSrKa/RUQYkTVv5fFi2896Btubva1caExE1tpM/yQL5YHnwQrMJty8/Yi8gSWbaRVXnY27YHHwt5Y9hFtQkqkIj8ceRcUTJGAtCvjnPXeISlQduJOZLIqZaIOSCdIfQUGEYVC9/GReTj0N9NfMz0MCH4indEGMzRDyqz4glzLiUYHST/Ct2twAeigFxWGKnMlFoImRa8wAHUJeh5M4+iygGcv5D/OLJn9E3HRnBigPQuJTF2R4KghJA3Y6wXGr0FTCfDrnjcJYoF8u8zGl4HJfYMFRF94zBGYRoy5/WZlHBEtFpT2682NXmR1Ufz1igDBpGw8E0=
  # GITHUB_TOKEN
    - secure: lK4h+uffcxiu9cpffJGsR+W2v5B1dpfXIhPcmw7ao7/YkPi0kBWpLXEUlSUUWozG+kk2Fxw0xk3yuGOsv8cV1rH/EChrWB8Z8B60OX92WJNBCmjQmdvxFcyrSnJyikrBjw0CuHypv6/vPqdQfBlia/Y2rGmdvMTdEd8fUdwD5XK2zVz+fisQboiurNx05YkNW3LV0cSAxPP9Nk9Sm4PcHLzgClss0/Ol2AamkiLfWNArddVqui5v2PtEVW4Tt+MnlSSGWqD6k5pkjibim3vCXSkkrmidYW1P2VQyjyKqYhBeFPpMlF8w544nEWGzAbFvWs8we+5PTndjERWd1g67FndGoqSehZmXNJ0k3a/jMSe8T+opIqxV2nnyM1GB3Fqm+mqVGSChM3mRu8YO3E8bm1wJQuiFlLthnENELuCHEOZsH61Xm99q3mut1wOodLnIOtr3/7HOODayI2i4Twy8tsmtiuZkVj97SYwPRqNPueeCwx2Aib7z9I6UeayC1a/2xPVrA7MITYybCs0SdW412IzzJkokZBphEBIgZDoBuvHjE67vPPj2OJso+wHUvjSEUgfQYfV6RZB4UPXWPy7bCFENljgN8wwANUxyjfNAmpOe8wOIyOFoNVbZzaUd9bVxbUkFZXt2q3kjoWFN1T5Soea+CpiFrCxmDUFvSzqr8RE=
